<?php

namespace UserControlBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use UserControlBundle\Entity\Rol;


/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{

    public function __construct(EntityManager $em)
    {
        $this->getEntityManager();
        parent::__construct($em, new Mapping\ClassMetadata(Rol::class));
    }

    public function findByName($rol)
    {
        return $this->createQueryBuilder('r')
            ->Where('r.name = :rol')
            ->setParameter('rol', $rol)
            ->getQuery()
        ;
    }

}
