services:
    sonata.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, UserControlBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: usuarios, label: User }

    sonata.rol:
        class: AppBundle\Admin\RolAdmin
        arguments: [~, UserControlBundle\Entity\Rol, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: usuarios, label: Rol }

    sonata.mensaje:
        class: AppBundle\Admin\MensajeAdmin
        arguments: [~, AppBundle\Entity\Mensaje, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: chat, label: Mensaje }

    sonata.noticia:
        class: AppBundle\Admin\NoticiaAdmin
        arguments: [~, AppBundle\Entity\Noticia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: noticias, label: Noticia }

    sonata.categoria:
        class: AppBundle\Admin\CategoriaAdmin
        arguments: [~, AppBundle\Entity\Categoria, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: noticias, label: Categoria }

#    sonata.ciclo:
#        class: AppBundle\Admin\CicloAdmin
#        arguments: [~, AppBundle\Entity\Ciclo, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Ciclo }

    app.admin.asignatura:
        class: AppBundle\Admin\AsignaturaAdmin
        arguments: [~, AppBundle\Entity\Asignatura, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: currículo, label: Asignatura }

    app.admin.sala:
        class: AppBundle\Admin\SalaAdmin
        arguments: [~, AppBundle\Entity\Sala, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: chat, label: Sala }
        calls:
            - [ addChild, [@sonata.user]]

    app.admin.ciclo:
        class: AppBundle\Admin\CicloAdmin
        arguments: [~, AppBundle\Entity\Ciclo, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: currículo, label: Ciclo }

    app.admin.sala.tipo:
        class: AppBundle\Admin\Sala_tipoAdmin
        arguments: [~, AppBundle\Entity\Sala_tipo, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: chat, label: Sala tipo }

    app.admin.curriculum:
        class: AppBundle\Admin\CurriculumAdmin
        arguments: [~, AppBundle\Entity\Curriculum, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: currículo, label: Curriculum }

    app.admin.titulo_fp:
        class: AppBundle\Admin\Titulo_fpAdmin
        arguments: [~, AppBundle\Entity\TituloFP, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: currículo, label: TituloFP }

    app.menu_listener:
          class: AppBundle\EventListener\MenuBuilderListener
          tags:
              - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    app.xls_file_users_importer:
        class: AppBundle\DataImport\XlsFileUsersImporter
        arguments: [@phpexcel, @repository.rol]

    app.xls_file_ciclos_importer:
        class: AppBundle\DataImport\XlsFileCiclosImporter
        arguments: [@phpexcel]